### ISSUE TITLE
Publish new version of nvpair

### ISSUE THREAD

**Issue by jgrund** [jmesmon/rust-libzfs#1]
Hi,

I'd like to use `nvpair` to consume a raw `nvlist_t`. Please publish a new version so I can use `NvList::from_ptr`.

**Comment by jmesmon** [comment]
Sure thing. The just released `0.2.0` version includes `NvList::from_ptr()`.

https://docs.rs/nvpair/0.2.0/nvpair/struct.NvList.html#method.from_ptr
https://crates.io/crates/nvpair/0.2.0
