### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by fabianfreyer** [jmesmon/rust-libzfs#10]
Would it be possible to license these, ideally under MIT or BSD licenses?

**Comment by jmesmon** [comment]
The only Cargo.toml missing a license line was zfs-core. I've added the "Apache-2.0 OR MIT" line there (as was already in place in zfs-core-sys). It is true that this should also be added to the readme.

**Comment by fabianfreyer** [comment]
Thanks!
