### ISSUE TITLE
Rename to rust-libzfs_core and publish to crates.io?

### ISSUE THREAD

**Issue by dsheets** [jmesmon/rust-libzfs#5]
There currently exists <https://crates.io/crates/libzfs_core-sys> but it does not list a source repository and seems somewhat less developed. It would be great to have this package published there. Also, <https://github.com/whamcloud/rust-libzfs> seems to be `libzfs` bindings only and this repository is `libzfs_core` bindings only. I am using both in my project. It would be nice to have this repository named to reflect the fact that it binds to `libzfs_core`.

**Comment by jmesmon** [comment]
I'm open to both of these.

For publishing to crates.io, we'll need to pick a different name than `libzfs-core-sys` (as `libzfs_core-sys` will block it). Thoughts there? Maybe `zfs-core-sys`?

**Comment by fabianfreyer** [comment]
you could publish it as `zfs-core` and `zfs-core-sys`?

**Comment by jmesmon** [comment]
Done.
https://crates.io/crates/zfs-core
https://crates.io/crates/zfs-core-sys
